### ISSUE TITLE
webIrcJS - Mode support 

### ISSUE THREAD

**Issue by jyonxo** [ozjd/ircjs#1]
Ability to have a Mode event, need to know

Modes will be in raw format

UserMode and ChanMode if differentiated would be great

**Comment by realJoshByrnes** [comment]
MODE &lt;Ttarget&gt; &lt;...modes&gt;
Is there a valid reason to emit two seperate events @jyonxo ? The only way I can determine which is which is by parsing the target string - which may differ depending on network.

**Comment by realJoshByrnes** [comment]
Added mode in commit https://github.com/ozjd/ircjs/commit/0f799ed6bc4ddca11f4845bcae092a6aaaa345b6

I chose not to add umode/chmode differently as it would add a bunch of complexities to a pre-mature client. With that said, It's probably something I'd look at in the future.
