### ISSUE TITLE
webIrcJS - Nickname support

### ISSUE THREAD

**Issue by jyonxo** [ozjd/ircjs#2]
Ability to set a nickname before connecting

**Comment by realJoshByrnes** [comment]
setNickname() will be added.
When disconnected, it will set the local preferred nickname.
When connected to a network, it will ATTEMPT to change the nickname, with no guarantee that anything has happened (listen for the on('NICK') event.

**Comment by realJoshByrnes** [comment]
As promised, this is now implemented.

Format: ircJS.setNickname(<nickname>)

As an added bonus, '?' will translate to a single random digit.

eg ````ircJS.setNickname('>Webchat_????')```` might set a nickname of ````>Webchat_3850````
