### ISSUE TITLE
webIrcJS - No Part Event

### ISSUE THREAD

**Issue by jyonxo** [ozjd/ircjs#3]
As subject

**Comment by realJoshByrnes** [comment]
Although it's just not yet implemented, I've marked it as a bug as I think any IRC client should be able to process a PART event. Will implement today.

**Comment by jyonxo** [comment]
what a gentleman :)

**Comment by realJoshByrnes** [comment]
PART was added in commit https://github.com/ozjd/ircjs/commit/73d3db022ad74bf4cb0932ca9d03283f0fece9d5
